### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by ZhenningUNSW** [chayuto/Santas-Little-Helper#1]
I have problom building the project, I said that Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> java.io.FileNotFoundException: C:\Users\jiang\AndroidStudioProject\Santas-Little-Helper\app\libs\javax.activation.jar (The system cannot find the path specified)

Can you please commit this library to let me check whether I can build this project or not?

**Comment by chayuto** [comment]
Line removed in grade file 
compile ('libs\java.act.jar)
